{% set name = "awkward-cpp" %}
{% set version = "33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awkward-cpp-{{ version }}.tar.gz
  sha256: 550adebccd329d18d02e95226d0b89698188fd33e44f07450942c692881927d8

build:
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.15
    - make
  host:
    - python
    - pip
    - scikit-build-core >=0.2.0
    - pybind11
  run:
    - python
    - importlib-resources  # [py<39]
    - numpy >=1.18.0

test:
  imports:
    - awkward_cpp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/awkward-cpp/
  summary: CPU kernels and compiled extensions for Awkward Array
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - rapidjson/license.txt
    - rapidjson/bin/jsonschema/LICENSE

extra:
  recipe-maintainers:
    - henryiii
    - conda-forge/awkward
    - conda-forge/scikit-hep
