{% set name = "awkward-cpp" %}
{% set version = "37" %}
{% set build = 2 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6dff5fce4afcadb492bbf7cb20908572d99bdc32aa2bea8681bacfb69b2aa86d

build:
  # Prioritize builds with a higher microarch level.
  # microarch_level 4 not supported yet.
  # c.f. https://github.com/conda-forge/microarch-level-feedstock/issues/5
  number: {{ build }}          # [not (unix and x86_64)]
  number: {{ build + 100 }}    # [unix and x86_64 and microarch_level == 1]
  number: {{ build + 300 }}    # [unix and x86_64 and microarch_level == 3]
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - x86_64-microarch-level {{ microarch_level }}  # [unix and x86_64]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.15
    - make
  host:
    - python
    - pip
    - scikit-build-core >=0.2.0
    - pybind11
  run:
    - python
    - importlib-resources  # [py<39]
    - numpy >=1.18.0

test:
  imports:
    - awkward_cpp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/awkward-cpp/
  summary: CPU kernels and compiled extensions for Awkward Array
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - rapidjson/license.txt
    - rapidjson/bin/jsonschema/LICENSE

extra:
  recipe-maintainers:
    - henryiii
    - conda-forge/awkward
    - conda-forge/scikit-hep
