context:
  version: "47"

package:
  name: awkward-cpp
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/awkward-cpp/awkward_cpp-${{ version }}.tar.gz
  sha256: 676cf4976810edab32187edf5a8a716af95047b9038c96d27d3be44f1331950f

build:
  number: 0
  variant:
    use_keys:
      - x86_64_microarch_level
    down_prioritize_variant: ${{ 0 if x86_64_microarch_level == 1 else 1 }}
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - if: unix and x86_64
      then: x86_64-microarch-level ==${{ x86_64_microarch_level }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake >=3.15
    - if: unix
      then: make
  host:
    - python
    - pip
    - scikit-build-core >=0.2.0
    - pybind11
  run:
    - python
    - if: python <3.9
      then: importlib-resources
    - numpy >=1.18.0

tests:
  - python:
      imports:
        - awkward_cpp
      pip_check: true

about:
  homepage: https://pypi.org/project/awkward-cpp/
  summary: CPU kernels and compiled extensions for Awkward Array
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - rapidjson/license.txt

extra:
  recipe-maintainers:
    - henryiii
    - conda-forge/awkward
    - conda-forge/scikit-hep
