context:
  name: "awkward-cpp"
  version: "50"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name|replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 264b6fb4e82acc1057b5b2ff0d33fabc361032528e233815cd2224c6dbc96d8e

build:
  number: 0
  variant:
    use_keys:
      - x86_64_microarch_level
    down_prioritize_variant: ${{ 0 if x86_64_microarch_level == 1 else 1 }}
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    # c.f. https://github.com/conda-forge/awkward-cpp-feedstock/pull/67#issuecomment-3073170539
    - if: unix and x86_64
      then: x86_64-microarch-level ${{ '==' ~ x86_64_microarch_level if x86_64_microarch_level else "*" }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake >=3.15
    - if: unix
      then: make
  host:
    - python
    - pip
    - scikit-build-core >=0.2.0
    - pybind11
  run:
    - python
    - if: python <3.9
      then: importlib-resources
    - numpy >=1.18.0

tests:
  - python:
      imports:
        - awkward_cpp
      pip_check: true

about:
  homepage: https://pypi.org/project/awkward-cpp/
  summary: CPU kernels and compiled extensions for Awkward Array
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - rapidjson/license.txt

extra:
  recipe-maintainers:
    - henryiii
    - conda-forge/awkward
    - conda-forge/scikit-hep
